### ISSUE TITLE
chai-json not working

### ISSUE THREAD

**Issue by skumar568** [giper45/chai-json#1]
Hi,

I tried to follow the documentation and written below:-
const chai = require('chai');
chai.use(require('chai-json'));
const expect = chai.expect;
describe('test project components', () => {
    it('should have package.json', () => {
        expect('./hi.json').to.be.a.jsonFile();
    });
});

I am getting below error:-
 Error: Invalid Chai property: jsonFile
      at Error (native)
      at Object.proxyGetter [as get] (node_modules\chai\lib\chai\utils\proxify.js:66:17)
      at Context.it (test\project.spec.js:10:36)

Similar issue is with other chai plugins (chai-js) that I tested. Am I missing anything?

Regards,
Sanjeev

**Comment by giper45** [comment]
Hi @skumar568, your syntax is correct.
 Could you tell me which nodejs and chai version are you using?
 If you're using chai v4.x.x could you try to downgrade chai to version 3 (try 3.5.0) and retry to use chai-json, chai-js and other plugins with this issue  ? 
Maybe these library has incompatibility with newer chai version.

**Comment by skumar568** [comment]
Thanks @giper45 . It seems like two issues are there:-

1. With chai@^4.1.0, plug-in doesn't work. Have to use chai@3.5.0
2. Syntax mentioned in read-me is not correct.
   expect(testFile).to.be.a.jsonFile(); : doesn't work
   expect(testFile).to.be.a.jsonFile; : it works

**Comment by giper45** [comment]
Hi @skumar568 

> With chai@^4.1.0, plug-in doesn't work. Have to use chai@3.5.0

Ok, I'll try to fix this, that's a common issue that affect different plugins, I have to find a solution to keep backward compatibility, or I just add to readme that my plugin needs chai version 3.x.x.

> Syntax mentioned in read-me is not correct.

This is a strange, because the syntax in readme is the correct syntax... you shouldn't trust about the second syntax because I think that it always gives true (try to use that syntax with a no existent file or with a json file with a wrong syntax). 
Can you send me the testFile.json file are you using and which error it gives so I try to fix the problem? Now I restart to work to the plugin to resolve these issues ;) 
Thanks for your collaboration!

**Comment by adamcohen** [comment]
same issue for me, any progress on this?

**Comment by giper45** [comment]
Hi, can you give a Json file sample that gives  this error in order to debug it? Thanks!

**Comment by giper45** [comment]
Sorry, I'm not able to reproduce it, I'd ask:
- mocha version 
- chai version 
- node version
- a json file in order to test

**Comment by 9wick** [comment]
Hi,
Same issue occurred to me.(Invalid Chai property: jsonFile)
and After I changed code, it works.

https://github.com/9wick/chai-json/commit/4cc62ae4e2e626a5138538eb8c41e1dffe62819f

**Comment by giper45** [comment]
Thx @9wick  ! I've just inserted your fix !
